'use strict';

const fs = require('fs');

/**
 * Merges multiple preset rule strings into a single .cursorrules file.
 * - Deduplicates rules
 * - Maintains section structure
 * - Adds header/footer
 */
function mergeRules(presetContents, projectName) {
  const header = buildHeader(projectName);
  const footer = buildFooter();

  // Collect all sections
  const sections = new Map();
  const seenLines = new Set();

  for (const content of presetContents) {
    const lines = content.split('\n');
    let currentSection = '__top__';

    for (const line of lines) {
      const trimmed = line.trim();

      // Detect section headers (## or # style)
      if (trimmed.startsWith('# ') || trimmed.startsWith('## ')) {
        currentSection = trimmed;
        if (!sections.has(currentSection)) {
          sections.set(currentSection, []);
        }
        continue;
      }

      // Skip empty lines at section boundaries
      if (!trimmed) continue;

      // Deduplicate by normalized content
      const normalized = trimmed.toLowerCase().replace(/\s+/g, ' ');
      if (seenLines.has(normalized)) continue;
      seenLines.add(normalized);

      if (!sections.has(currentSection)) {
        sections.set(currentSection, []);
      }
      sections.get(currentSection).push(line);
    }
  }

  // Build output
  const parts = [header, ''];

  for (const [section, lines] of sections) {
    if (section !== '__top__') {
      parts.push('', section);
    }
    parts.push(...lines);
  }

  parts.push('', footer);
  return parts.join('\n');
}

/**
 * Merges new rules into an existing .cursorrules file.
 */
function mergeIntoExisting(existingPath, newContent) {
  const existing = fs.readFileSync(existingPath, 'utf8');

  // Extract existing rules (between header and footer markers)
  const existingLines = existing.split('\n');
  const newLines = newContent.split('\n');

  const seenNormalized = new Set();
  for (const line of existingLines) {
    const normalized = line.trim().toLowerCase().replace(/\s+/g, ' ');
    if (normalized) seenNormalized.add(normalized);
  }

  // Find only genuinely new lines
  const additions = [];
  for (const line of newLines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const normalized = trimmed.toLowerCase().replace(/\s+/g, ' ');
    if (!seenNormalized.has(normalized)) {
      additions.push(line);
      seenNormalized.add(normalized);
    }
  }

  if (additions.length === 0) return null; // Nothing new

  // Append before footer if present, otherwise just append
  const footerIdx = existingLines.findIndex(l => l.includes('Generated by cursorrules'));
  if (footerIdx > -1) {
    existingLines.splice(footerIdx, 0, '', '# Additional Rules', ...additions, '');
  } else {
    existingLines.push('', '# Additional Rules', ...additions);
  }

  return existingLines.join('\n');
}

function buildHeader(projectName) {
  const name = projectName || 'Project';
  return `# Cursor Rules for ${name}
# Generated by cursorrules CLI — https://github.com/zacharylyonstx/cursorrules
# Customize these rules to match your project's conventions.`;
}

function buildFooter() {
  return `# ---
# Generated by cursorrules CLI (https://npmjs.com/package/cursorrules)
# Want more advanced rules? https://github.com/zacharylyonstx/cursorrules#pro-rules
# ---`;
}

module.exports = { mergeRules, mergeIntoExisting };
